// Code generated by golex. DO NOT EDIT.

// Copyright 2017 The WL Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wl

import (
	"fmt"

	"github.com/cznic/golex/lex"
)

func (lx *lexer) scan() (r int) {
	// fmt.Printf("%T.scan\n", lx)
	// defer func() { fmt.Printf("\t%T.scan: %U %s\n", lx, r, yySymName(r)) }()
	c := lx.Enter()

	/* classes */

yystate0:
	yyrule := -1
	_ = yyrule
	c = lx.Rule0()

	switch yyt := lx.sc; yyt {
	default:
		panic(fmt.Errorf(`invalid start condition %d`, yyt))
	case 0: // start condition: INITIAL
		goto yystart1
	case 1: // start condition: S
		goto yystart90
	}

	goto yystate0 // silence unused label error
	goto yyAction // silence unused label error
yyAction:
	switch yyrule {
	case 1:
		goto yyrule1
	case 2:
		goto yyrule2
	case 3:
		goto yyrule3
	case 4:
		goto yyrule4
	case 5:
		goto yyrule5
	case 6:
		goto yyrule6
	case 7:
		goto yyrule7
	case 8:
		goto yyrule8
	case 9:
		goto yyrule9
	case 10:
		goto yyrule10
	case 11:
		goto yyrule11
	case 12:
		goto yyrule12
	case 13:
		goto yyrule13
	case 14:
		goto yyrule14
	case 15:
		goto yyrule15
	case 16:
		goto yyrule16
	case 17:
		goto yyrule17
	case 18:
		goto yyrule18
	case 19:
		goto yyrule19
	case 20:
		goto yyrule20
	case 21:
		goto yyrule21
	case 22:
		goto yyrule22
	case 23:
		goto yyrule23
	case 24:
		goto yyrule24
	case 25:
		goto yyrule25
	case 26:
		goto yyrule26
	case 27:
		goto yyrule27
	case 28:
		goto yyrule28
	case 29:
		goto yyrule29
	case 30:
		goto yyrule30
	case 31:
		goto yyrule31
	case 32:
		goto yyrule32
	case 33:
		goto yyrule33
	case 34:
		goto yyrule34
	case 35:
		goto yyrule35
	case 36:
		goto yyrule36
	case 37:
		goto yyrule37
	case 38:
		goto yyrule38
	case 39:
		goto yyrule39
	case 40:
		goto yyrule40
	case 41:
		goto yyrule41
	case 42:
		goto yyrule42
	case 43:
		goto yyrule43
	case 44:
		goto yyrule44
	case 45:
		goto yyrule45
	case 46:
		goto yyrule46
	case 47:
		goto yyrule47
	case 48:
		goto yyrule48
	case 49:
		goto yyrule49
	case 50:
		goto yyrule50
	case 51:
		goto yyrule51
	case 52:
		goto yyrule52
	case 53:
		goto yyrule53
	case 54:
		goto yyrule54
	case 55:
		goto yyrule55
	case 56:
		goto yyrule56
	case 57:
		goto yyrule57
	case 58:
		goto yyrule58
	case 59:
		goto yyrule59
	case 60:
		goto yyrule60
	case 61:
		goto yyrule61
	case 62:
		goto yyrule62
	case 63:
		goto yyrule63
	}
	goto yystate1 // silence unused label error
yystate1:
	c = lx.Next()
yystart1:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate3
	case c == '#':
		goto yystate4
	case c == '$' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c == '\u0082' || c == '\u0083':
		goto yystate11
	case c == '&':
		goto yystate20
	case c == '(':
		goto yystate23
	case c == '+':
		goto yystate27
	case c == '-':
		goto yystate29
	case c == '.':
		goto yystate32
	case c == '/':
		goto yystate37
	case c == ':':
		goto yystate49
	case c == '<':
		goto yystate53
	case c == '=':
		goto yystate57
	case c == '>':
		goto yystate62
	case c == '@':
		goto yystate64
	case c == '[':
		goto yystate68
	case c == '\'':
		goto yystate22
	case c == '\\':
		goto yystate70
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate2
	case c == '\u0084':
		goto yystate82
	case c == '\u0085':
		goto yystate83
	case c == '\u0086':
		goto yystate84
	case c == '\u0087':
		goto yystate85
	case c == '\u0088':
		goto yystate86
	case c == '\u0089':
		goto yystate87
	case c == '\u008a':
		goto yystate88
	case c == '\u008b':
		goto yystate89
	case c == ']':
		goto yystate77
	case c == '_':
		goto yystate12
	case c == '`':
		goto yystate79
	case c == '|':
		goto yystate80
	case c >= '0' && c <= '9':
		goto yystate45
	}

yystate2:
	c = lx.Next()
	yyrule = 1
	lx.Mark()
	switch {
	default:
		goto yyrule1
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate2
	}

yystate3:
	c = lx.Next()
	yyrule = 3
	lx.Mark()
	goto yyrule3

yystate4:
	c = lx.Next()
	yyrule = 63
	lx.Mark()
	switch {
	default:
		goto yyrule63
	case c == '$' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c == '\u0082' || c == '\u0083':
		goto yystate5
	case c == '`':
		goto yystate10
	case c >= '0' && c <= '9':
		goto yystate9
	}

yystate5:
	c = lx.Next()
	yyrule = 63
	lx.Mark()
	switch {
	default:
		goto yyrule63
	case c == '$' || c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c >= '\u0081' && c <= '\u0083':
		goto yystate5
	case c == '`':
		goto yystate6
	}

yystate6:
	c = lx.Next()
	yyrule = 63
	lx.Mark()
	switch {
	default:
		goto yyrule63
	case c == '$' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c == '\u0082' || c == '\u0083':
		goto yystate7
	}

yystate7:
	c = lx.Next()
	yyrule = 63
	lx.Mark()
	switch {
	default:
		goto yyrule63
	case c == '$' || c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c >= '\u0081' && c <= '\u0083':
		goto yystate7
	case c == '`':
		goto yystate8
	}

yystate8:
	c = lx.Next()
	yyrule = 63
	lx.Mark()
	goto yyrule63

yystate9:
	c = lx.Next()
	yyrule = 63
	lx.Mark()
	switch {
	default:
		goto yyrule63
	case c >= '0' && c <= '9':
		goto yystate9
	}

yystate10:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '$' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c == '\u0082' || c == '\u0083':
		goto yystate7
	}

yystate11:
	c = lx.Next()
	yyrule = 60
	lx.Mark()
	switch {
	default:
		goto yyrule60
	case c == '$' || c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c >= '\u0081' && c <= '\u0083':
		goto yystate11
	case c == '_':
		goto yystate12
	case c == '`':
		goto yystate17
	}

yystate12:
	c = lx.Next()
	yyrule = 62
	lx.Mark()
	switch {
	default:
		goto yyrule62
	case c == '$' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c == '\u0082' || c == '\u0083':
		goto yystate13
	case c == '.':
		goto yystate14
	case c == '_':
		goto yystate15
	}

yystate13:
	c = lx.Next()
	yyrule = 62
	lx.Mark()
	switch {
	default:
		goto yyrule62
	case c == '$' || c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c >= '\u0081' && c <= '\u0083':
		goto yystate13
	case c == '.':
		goto yystate14
	}

yystate14:
	c = lx.Next()
	yyrule = 62
	lx.Mark()
	goto yyrule62

yystate15:
	c = lx.Next()
	yyrule = 62
	lx.Mark()
	switch {
	default:
		goto yyrule62
	case c == '$' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c == '\u0082' || c == '\u0083':
		goto yystate13
	case c == '.':
		goto yystate14
	case c == '_':
		goto yystate16
	}

yystate16:
	c = lx.Next()
	yyrule = 62
	lx.Mark()
	switch {
	default:
		goto yyrule62
	case c == '$' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c == '\u0082' || c == '\u0083':
		goto yystate13
	case c == '.':
		goto yystate14
	}

yystate17:
	c = lx.Next()
	yyrule = 60
	lx.Mark()
	switch {
	default:
		goto yyrule60
	case c == '$' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c == '\u0082' || c == '\u0083':
		goto yystate18
	}

yystate18:
	c = lx.Next()
	yyrule = 60
	lx.Mark()
	switch {
	default:
		goto yyrule60
	case c == '$' || c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c >= '\u0081' && c <= '\u0083':
		goto yystate18
	case c == '`':
		goto yystate19
	}

yystate19:
	c = lx.Next()
	yyrule = 60
	lx.Mark()
	goto yyrule60

yystate20:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '&':
		goto yystate21
	}

yystate21:
	c = lx.Next()
	yyrule = 18
	lx.Mark()
	goto yyrule18

yystate22:
	c = lx.Next()
	yyrule = 19
	lx.Mark()
	goto yyrule19

yystate23:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '*':
		goto yystate24
	}

yystate24:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '*':
		goto yystate25
	case c >= '\x01' && c <= ')' || c >= '+' && c <= '\u007f' || c >= '\u0081' && c <= 'ÿ':
		goto yystate24
	}

yystate25:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate26
	case c == '*':
		goto yystate25
	case c >= '\x01' && c <= '(' || c >= '+' && c <= '\u007f' || c >= '\u0081' && c <= 'ÿ':
		goto yystate24
	}

yystate26:
	c = lx.Next()
	yyrule = 2
	lx.Mark()
	goto yyrule2

yystate27:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '+':
		goto yystate28
	}

yystate28:
	c = lx.Next()
	yyrule = 20
	lx.Mark()
	goto yyrule20

yystate29:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '-':
		goto yystate30
	case c == '>':
		goto yystate31
	}

yystate30:
	c = lx.Next()
	yyrule = 21
	lx.Mark()
	goto yyrule21

yystate31:
	c = lx.Next()
	yyrule = 22
	lx.Mark()
	goto yyrule22

yystate32:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate33
	}

yystate33:
	c = lx.Next()
	yyrule = 59
	lx.Mark()
	switch {
	default:
		goto yyrule59
	case c == '`':
		goto yystate34
	case c >= '0' && c <= '9':
		goto yystate33
	}

yystate34:
	c = lx.Next()
	yyrule = 59
	lx.Mark()
	switch {
	default:
		goto yyrule59
	case c == '`':
		goto yystate36
	case c >= '0' && c <= '9':
		goto yystate35
	}

yystate35:
	c = lx.Next()
	yyrule = 59
	lx.Mark()
	switch {
	default:
		goto yyrule59
	case c >= '0' && c <= '9':
		goto yystate35
	}

yystate36:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate35
	}

yystate37:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '*':
		goto yystate38
	case c == '.':
		goto yystate39
	case c == '/':
		goto yystate40
	case c == ';':
		goto yystate43
	case c == '@':
		goto yystate44
	}

yystate38:
	c = lx.Next()
	yyrule = 23
	lx.Mark()
	goto yyrule23

yystate39:
	c = lx.Next()
	yyrule = 24
	lx.Mark()
	goto yyrule24

yystate40:
	c = lx.Next()
	yyrule = 25
	lx.Mark()
	switch {
	default:
		goto yyrule25
	case c == '.':
		goto yystate41
	case c == '@':
		goto yystate42
	}

yystate41:
	c = lx.Next()
	yyrule = 26
	lx.Mark()
	goto yyrule26

yystate42:
	c = lx.Next()
	yyrule = 27
	lx.Mark()
	goto yyrule27

yystate43:
	c = lx.Next()
	yyrule = 28
	lx.Mark()
	goto yyrule28

yystate44:
	c = lx.Next()
	yyrule = 29
	lx.Mark()
	goto yyrule29

yystate45:
	c = lx.Next()
	yyrule = 61
	lx.Mark()
	switch {
	default:
		goto yyrule61
	case c == '.':
		goto yystate33
	case c == '^':
		goto yystate46
	case c >= '0' && c <= '9':
		goto yystate45
	}

yystate46:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '^':
		goto yystate47
	}

yystate47:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate32
	case c >= '0' && c <= '9':
		goto yystate48
	}

yystate48:
	c = lx.Next()
	yyrule = 61
	lx.Mark()
	switch {
	default:
		goto yyrule61
	case c == '.':
		goto yystate33
	case c >= '0' && c <= '9':
		goto yystate48
	}

yystate49:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == ':':
		goto yystate50
	case c == '=':
		goto yystate51
	case c == '>':
		goto yystate52
	}

yystate50:
	c = lx.Next()
	yyrule = 30
	lx.Mark()
	goto yyrule30

yystate51:
	c = lx.Next()
	yyrule = 31
	lx.Mark()
	goto yyrule31

yystate52:
	c = lx.Next()
	yyrule = 32
	lx.Mark()
	goto yyrule32

yystate53:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '<':
		goto yystate54
	case c == '=':
		goto yystate55
	case c == '>':
		goto yystate56
	}

yystate54:
	c = lx.Next()
	yyrule = 33
	lx.Mark()
	goto yyrule33

yystate55:
	c = lx.Next()
	yyrule = 34
	lx.Mark()
	goto yyrule34

yystate56:
	c = lx.Next()
	yyrule = 35
	lx.Mark()
	goto yyrule35

yystate57:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '!':
		goto yystate58
	case c == '=':
		goto yystate60
	}

yystate58:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '=':
		goto yystate59
	}

yystate59:
	c = lx.Next()
	yyrule = 36
	lx.Mark()
	goto yyrule36

yystate60:
	c = lx.Next()
	yyrule = 37
	lx.Mark()
	switch {
	default:
		goto yyrule37
	case c == '=':
		goto yystate61
	}

yystate61:
	c = lx.Next()
	yyrule = 38
	lx.Mark()
	goto yyrule38

yystate62:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '=':
		goto yystate63
	}

yystate63:
	c = lx.Next()
	yyrule = 39
	lx.Mark()
	goto yyrule39

yystate64:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '*':
		goto yystate65
	case c == '@':
		goto yystate66
	}

yystate65:
	c = lx.Next()
	yyrule = 40
	lx.Mark()
	goto yyrule40

yystate66:
	c = lx.Next()
	yyrule = 41
	lx.Mark()
	switch {
	default:
		goto yyrule41
	case c == '@':
		goto yystate67
	}

yystate67:
	c = lx.Next()
	yyrule = 42
	lx.Mark()
	goto yyrule42

yystate68:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '[':
		goto yystate69
	}

yystate69:
	c = lx.Next()
	yyrule = 43
	lx.Mark()
	goto yyrule43

yystate70:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '%':
		goto yystate71
	case c == '&':
		goto yystate72
	case c == '+':
		goto yystate73
	case c == '@':
		goto yystate74
	case c == '^':
		goto yystate75
	case c == '_':
		goto yystate76
	}

yystate71:
	c = lx.Next()
	yyrule = 44
	lx.Mark()
	goto yyrule44

yystate72:
	c = lx.Next()
	yyrule = 45
	lx.Mark()
	goto yyrule45

yystate73:
	c = lx.Next()
	yyrule = 46
	lx.Mark()
	goto yyrule46

yystate74:
	c = lx.Next()
	yyrule = 47
	lx.Mark()
	goto yyrule47

yystate75:
	c = lx.Next()
	yyrule = 48
	lx.Mark()
	goto yyrule48

yystate76:
	c = lx.Next()
	yyrule = 49
	lx.Mark()
	goto yyrule49

yystate77:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == ']':
		goto yystate78
	}

yystate78:
	c = lx.Next()
	yyrule = 51
	lx.Mark()
	goto yyrule51

yystate79:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '$' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c == '\u0082' || c == '\u0083':
		goto yystate18
	}

yystate80:
	c = lx.Next()
	switch {
	default:
		goto yyabort
	case c == '|':
		goto yystate81
	}

yystate81:
	c = lx.Next()
	yyrule = 50
	lx.Mark()
	goto yyrule50

yystate82:
	c = lx.Next()
	yyrule = 17
	lx.Mark()
	goto yyrule17

yystate83:
	c = lx.Next()
	yyrule = 53
	lx.Mark()
	goto yyrule53

yystate84:
	c = lx.Next()
	yyrule = 58
	lx.Mark()
	goto yyrule58

yystate85:
	c = lx.Next()
	yyrule = 52
	lx.Mark()
	goto yyrule52

yystate86:
	c = lx.Next()
	yyrule = 55
	lx.Mark()
	goto yyrule55

yystate87:
	c = lx.Next()
	yyrule = 57
	lx.Mark()
	goto yyrule57

yystate88:
	c = lx.Next()
	yyrule = 56
	lx.Mark()
	goto yyrule56

yystate89:
	c = lx.Next()
	yyrule = 54
	lx.Mark()
	goto yyrule54

	goto yystate90 // silence unused label error
yystate90:
	c = lx.Next()
yystart90:
	switch {
	default:
		goto yystate92 // c >= '\x01' && c <= '!' || c >= '#' && c <= '[' || c >= ']' && c <= '\u0083' || c >= '\u0085' && c <= 'ÿ'
	case c == '"':
		goto yystate93
	case c == '\\':
		goto yystate94
	case c == '\u0084':
		goto yystate104
	case c == '\x00':
		goto yystate91
	}

yystate91:
	c = lx.Next()
	yyrule = 4
	lx.Mark()
	goto yyrule4

yystate92:
	c = lx.Next()
	yyrule = 15
	lx.Mark()
	goto yyrule15

yystate93:
	c = lx.Next()
	yyrule = 16
	lx.Mark()
	goto yyrule16

yystate94:
	c = lx.Next()
	yyrule = 15
	lx.Mark()
	switch {
	default:
		goto yyrule15
	case c == ' ':
		goto yystate96
	case c == '"':
		goto yystate97
	case c == '\\':
		goto yystate98
	case c == '\n':
		goto yystate95
	case c == 'b':
		goto yystate99
	case c == 'f':
		goto yystate100
	case c == 'n':
		goto yystate101
	case c == 'r':
		goto yystate102
	case c == 't':
		goto yystate103
	}

yystate95:
	c = lx.Next()
	yyrule = 13
	lx.Mark()
	goto yyrule13

yystate96:
	c = lx.Next()
	yyrule = 6
	lx.Mark()
	goto yyrule6

yystate97:
	c = lx.Next()
	yyrule = 7
	lx.Mark()
	goto yyrule7

yystate98:
	c = lx.Next()
	yyrule = 5
	lx.Mark()
	goto yyrule5

yystate99:
	c = lx.Next()
	yyrule = 8
	lx.Mark()
	goto yyrule8

yystate100:
	c = lx.Next()
	yyrule = 11
	lx.Mark()
	goto yyrule11

yystate101:
	c = lx.Next()
	yyrule = 10
	lx.Mark()
	goto yyrule10

yystate102:
	c = lx.Next()
	yyrule = 12
	lx.Mark()
	goto yyrule12

yystate103:
	c = lx.Next()
	yyrule = 9
	lx.Mark()
	goto yyrule9

yystate104:
	c = lx.Next()
	yyrule = 14
	lx.Mark()
	goto yyrule14

yyrule1: // [ \t\r]+

	goto yystate0
yyrule2: // "(*"([^*\x80]|\*+[^*)\x80])*\*+\)

	goto yystate0
yyrule3: // \"
	{
		lx.sc = 1
		lx.str = lx.str[:0]
		goto yystate0
	}
yyrule4: // \x00
	{
		lx.str = append(lx.str, 0)
		goto yystate0
	}
yyrule5: // \\\\
	{
		lx.str = append(lx.str, '\\')
		goto yystate0
	}
yyrule6: // \\\x20
	{
		lx.str = append(lx.str, ' ')
		goto yystate0
	}
yyrule7: // \\\"
	{
		lx.str = append(lx.str, '"')
		goto yystate0
	}
yyrule8: // \\b
	{
		lx.str = append(lx.str, '\b')
		goto yystate0
	}
yyrule9: // \\t
	{
		lx.str = append(lx.str, '\t')
		goto yystate0
	}
yyrule10: // \\n
	{
		lx.str = append(lx.str, '\n')
		goto yystate0
	}
yyrule11: // \\f
	{
		lx.str = append(lx.str, '\f')
		goto yystate0
	}
yyrule12: // \\r
	{
		lx.str = append(lx.str, '\r')
		goto yystate0
	}
yyrule13: // \\\n

	goto yystate0
yyrule14: // {ignore}

	goto yystate0
yyrule15: // {schar}
	{

		lx.str = append(lx.str, lx.TokenBytes(nil)...)
		goto yystate0
	}
yyrule16: // \"
	{
		lx.sc = 0
		return STRING
	}
yyrule17: // {ignore}
	{

		return IGNORE
	}
yyrule18: // "&&"
	{
		return AND
	}
yyrule19: // "'"
	{
		return QUOTE
	}
yyrule20: // "++"
	{
		return INC
	}
yyrule21: // "--"
	{
		return DEC
	}
yyrule22: // "->"
	{
		return RULE
	}
yyrule23: // "/*"
	{
		return RIGHT_COMPOSITION
	}
yyrule24: // "/."
	{
		return REPLACEALL
	}
yyrule25: // "//"
	{
		return POSTFIX
	}
yyrule26: // "//."
	{
		return REPLACEREP
	}
yyrule27: // "//@"
	{
		return MAP_ALL
	}
yyrule28: // "/;"
	{
		return CONDITION
	}
yyrule29: // "/@"
	{
		return MAP
	}
yyrule30: // "::"
	{
		return MESSAGE_NAME
	}
yyrule31: // ":="
	{
		return SET_DELAYED
	}
yyrule32: // ":>"
	{
		return RULEDELAYED
	}
yyrule33: // "<<"
	{
		return GET
	}
yyrule34: // "<="
	{
		return LEQ
	}
yyrule35: // "<>"
	{
		return STRINGJOIN
	}
yyrule36: // "=!="
	{
		return UNSAME
	}
yyrule37: // "=="
	{
		return EQUAL
	}
yyrule38: // "==="
	{
		return SAME
	}
yyrule39: // ">="
	{
		return GEQ
	}
yyrule40: // "@*"
	{
		return COMPOSITION
	}
yyrule41: // "@@"
	{
		return APPLY
	}
yyrule42: // "@@@"
	{
		return APPLY_ALL
	}
yyrule43: // "[["
	{
		return lx.push(LPART)
	}
yyrule44: // "\%"
	{
		return POWER_SUBSCRIPT2
	}
yyrule45: // "\&"
	{
		return OVERSCRIPT
	}
yyrule46: // "\+"
	{
		return UNDERSCRIPT
	}
yyrule47: // "\@"
	{
		return SQRT2
	}
yyrule48: // "\^"
	{
		return POWER_SUBSCRIPT1
	}
yyrule49: // "\_"
	{
		return SUBSCRIPT
	}
yyrule50: // "||"
	{
		return OR
	}
yyrule51: // "]]"
	{
		if lx.pop() == LPART {
			return RPART
		}
		if la := lx.Lookahead(); la.Rune != 0 {
			lx.Unget(la)
		}
		lx.Unget(lex.NewChar(lx.First.Pos()+1, ']'))
		return ']'
	}
yyrule52: // {ConjugateTranspose}
	{
		return CONJUGATE_TRANSPOSE
	}
yyrule53: // {Conjugate}
	{
		return CONJUGATE
	}
yyrule54: // {DifferentialD}
	{
		return DIFFERENTIAL_D
	}
yyrule55: // {HermitianConjugate}
	{
		return HERMITIAN_CONJUGATE
	}
yyrule56: // {Integrate}
	{
		return INTEGRATE
	}
yyrule57: // {Sqrt}
	{
		return SQRT
	}
yyrule58: // {Transpose}
	{
		return TRANSPOSE
	}
yyrule59: // {float}
	{
		return FLOAT
	}
yyrule60: // {ident}
	{
		return IDENT
	}
yyrule61: // {int}
	{
		return INT
	}
yyrule62: // {pattern}
	{
		return PATTERN
	}
yyrule63: // {slot}
	{
		return SLOT
	}
	panic("unreachable")

	goto yyabort // silence unused label error

yyabort: // no lexem recognized
	if c, ok := lx.Abort(); ok {
		switch c {
		case '(', '[', '{':
			lx.push(c)
		case ')', ']', '}':
			lx.pop()
		}
		return c
	}

	goto yyAction
}
